### ISSUE TITLE
help

### ISSUE THREAD

**Issue by projectscls1** [chandachewe10/loan-management-system#1]
Help with the SQl.sql file

**Comment by chandachewe10** [comment]
Please create a database and migrate the tables to have the sql file.

**Comment by tunsoekhaing** [comment]
Please create a database and migrate the tables to have the sql file.

Can we run script with 
1. php artisan migrate --path=database/migrations/2022_01_31_191309_create_reg_employee_msts_table.php
2. php artisan factories --path=database/factories/emailsubscriptionFactory.php
3. php artisan seeders --path=database/seeders/DatabaseSeeder.php

how can i run it?

**Comment by chandachewe10** [comment]
> Please create a database and migrate the tables to have the sql file.
> 
> Can we run script with
> 
> 1. php artisan migrate --path=database/migrations/2022_01_31_191309_create_reg_employee_msts_table.php
> 2. php artisan factories --path=database/factories/emailsubscriptionFactory.php
> 3. php artisan seeders --path=database/seeders/DatabaseSeeder.php
> 
> how can i run it?



@tunsoekhaing 
1. composer install --no-scripts
2. copy .env.example .env
3. php artisan config:clear
4. php artisan cache:clear
5. php artisan key:generate
6. php artisan migrate --path=database/migrations/2022_01_31_191309_create_reg_employee_msts_table.php
7. php artisan migrate
8. php artisan db:seed
