### ISSUE TITLE
.env.example

### ISSUE THREAD

**Issue by Mino187** [chandachewe10/loan-management-system#12]
Good day

Have followed steps until the copy .env.example file...

i cannot find this file in the LMS folder... kindly assist with steps
![image](https://github.com/chandachewe10/loan-management-system/assets/168069675/c843467c-9852-42ff-8775-ee4d56a289a3)

**Comment by Mino187** [comment]
Thank you for responding.. you're a great help. I'm new to this. First time installing something from github. So how can I open the file? Touch .env.example?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chandachewe10** [comment]
`sudo nano .env.example`

**Comment by Mino187** [comment]
Many thanks.


Kind regards,
[cid:b96985ec-edf1-4e38-a123-bc265e083eaf]

Mazwe Financial Services (Pty) Ltd.

This e-mail is intended only for the named person or entity to which it is addressed and contains valuable business information that is privileged, confidential and/or otherwise protected from disclosure. If you received this e-mail in error, any review, use, dissemination, distribution or copying of this e-mail is strictly prohibited. Please immediately notify us by "Reply" command and permanently delete the original and any copies or printouts thereof. Although this email and any attachments are believed to be free of any virus or other defect that might affect any computer system into which it is received and opened, no liability, whether direct or indirect, is accepted by Mazwe Financial Services Pty Ltd “Mazwe” nor the sender should this email be found to contain viruses. The views expressed in this email are, unless otherwise stated, those of the author and not those of Mazwe or its management. Mazwe is an authorised financial service provider in terms of the Financial Advisory and Intermediary Services Act 37 of 2002 and a registered credit provider in terms of the National Credit Act 34 of 2005.
________________________________
