### ISSUE TITLE
 Please tell me the installation steps. Thank you.

### ISSUE THREAD

**Issue by suminoaapico** [chandachewe10/loan-management-system#13]
Please tell me the installation steps. Thank you.

**Comment by tolaleng** [comment]
I tried to install many times on the different environments by following the guidelines but there is no work at all, issue with running compose updates and migrate DB not successful

**Comment by chandachewe10** [comment]
> I tried to install many times on the different environments by following the guidelines but there is no work at all, issue with running compose updates and migrate DB not successful

What version of PHP are you using?

**Comment by tolaleng** [comment]
I'm hositng with PHP 8.1 and now the composer update is run successfully, only migrate with DB as below error message:

Error
----------------

2023_12_16_130656_create_loan_settlement_forms_table .................... 11ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'loan_settlement_text' used in key specification without a key length (Connection: mysql, SQL: alter table `loan_settlement_forms` add unique `loan_settlement_forms_loan_settlement_text_unique`(`loan_settlement_text`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕ 
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

      +9 vendor frames 

  10  database/migrations/2023_12_16_130656_create_loan_settlement_forms_table.php:14
      Illuminate\Support\Facades\Facade::__callStatic()
      +24 vendor frames 

  35  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by tolaleng** [comment]
Any idea how to make it work?

**Comment by chandachewe10** [comment]
> Any idea how to make it work?



> Any idea how to make it work?

Try to reinstall have pushed some new changes which will fix your Issue
