### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by mosesmwale** [chandachewe10/loan-management-system#27]
When adding a new borrower, **badmethodcall** - Method Filament\Forms\Components\TextInput::relationship does not exist.

                    Forms\Components\TextInput::make('added_by')

                    ->prefixIcon('heroicon-o-user')

                    ->relationship('added_by', 'name')

                    ->preload()

                    ->searchable()

                    ->required(),

**Comment by chandachewe10** [comment]
Thanks will check it out
