### ISSUE TITLE
I followed the installation steps and came in to the login screen. But it keeps giving me a 404 error.

### ISSUE THREAD

**Issue by cdg1999010** [chandachewe10/loan-management-system#30]
I followed the installation steps and came in to the login screen. But it keeps giving me a 404 error. I have put a screenshot of the login connection error nearby. What is the reason for this? Please help me. Thank you very much!
![_20241118001956](https://github.com/user-attachments/assets/d45543a8-43cf-409e-8603-264f3943e59e)

**Comment by cdg1999010** [comment]
![20241118002328](https://github.com/user-attachments/assets/0134a724-f45f-4b60-b088-342ee4885029)
This problem has been bothering me for a long time and I have not been able to find the source of the problem. Have reinstalled several times. The problem persists!

**Comment by chandachewe10** [comment]
@cdg1999010 it seems the error has nothing to do with the application but rather your localhost configurations. 
Is `APP_URL=....` matching with your url in `.env` ?

**Comment by chandachewe10** [comment]
Hi @cdg1999010 am marking this one as closed please feel to raise another issue if the problem persists
