### ISSUE TITLE
problem of composer install --no-scripts 

### ISSUE THREAD

**Issue by mauphung** [chandachewe10/loan-management-system#4]
Please help me to install this problem.

composer install --no-scripts
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:884
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/DependencyResolver/Problem.php:366
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpspec/prophecy is locked to version 1.14.0 and an update of this package was not requested.
    - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.10) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.10) does not satisfy that requirement.
    - phpunit/phpunit 9.5.10 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[1.14.0].
    - phpunit/phpunit is locked to version 9.5.10 and an update of this package was not requested.

**Comment by mauphung** [comment]
To solve it I run following commands:
composer global self-update
composer update

then continue with the instruction and it's working.
Thanks.

**Comment by chandachewe10** [comment]
> Please help me to install this problem.
> 
> composer install --no-scripts Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:879 Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:884 Installing dependencies from lock file (including require-dev) Verifying lock file contents can be installed on current platform. Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/mau/composer.phar/src/Composer/DependencyResolver/Problem.php:366 Your lock file does not contain a compatible set of packages. Please run composer update.
> 
> Problem 1 - phpspec/prophecy is locked to version 1.14.0 and an update of this package was not requested. - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.10) does not satisfy that requirement. Problem 2 - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.10) does not satisfy that requirement. - phpunit/phpunit 9.5.10 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[1.14.0]. - phpunit/phpunit is locked to version 9.5.10 and an update of this package was not requested.

Sorry run `composer update` instead of  `composer install --no-scripts`. I will update the README soon
